# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tJFduvhOkimRR8Y1JCQEhMOcxDncN2sc
"""

Total = 0
for number in range(1, 51):
    Total += number
print("The sum of numbers from 1 to 50 is:",Total)