# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tJFduvhOkimRR8Y1JCQEhMOcxDncN2sc
"""

number = int(input("Enter an integer: "))

if number % 2 == 0:
    print("The number is Even.")
else:
    print("The number is Odd.")

number = int(input("Enter an integer: "))

if number % 2 == 0:
    print("The number is Even.")
else:
    print("The number is Odd.")